### ISSUE TITLE
Clicks not working

### ISSUE THREAD

**Issue by Kluskey** [indrimuska/angular-moment-picker#51]
Just noticed this in the most recent commit. I can't always open the picker, and when I do, the click doesn't actually change the scope variable.

**Comment by indrimuska** [comment]
Hi @Kluskey, thank you for reporting this.
In the latest version I've changed the way to open/close the picker for performance gain and to be able to navigate the picker using the keyboard. Anyway, I don't understand what you mean with "it doesn't change the scope".

Can you please further argue your issue and provide an example showing that?

**Comment by nathalietran** [comment]
Hi @indrimuska, 

Indeed there is a problem with the 'click'. You can open the picker, however when clicking (with a click) on a date the date variable doesn't update.

However it works when hitting "enter" with the keyboard.

Thanks

**Comment by vedard** [comment]
Hi @indrimuska, 

I have the exact same issue, I test it on Chrome and Firefox. Everything work fine with the keyboard, but with with the mouse the picker always close when you click something.

![issue](https://cloud.githubusercontent.com/assets/8711046/18035845/b67f2bb4-6d2b-11e6-8852-5ad5dca491fb.gif)

**Comment by micflan** [comment]
This issue is also evident in the demo page examples http://indrimuska.github.io/angular-moment-picker/

**Comment by fourgates** [comment]
I was having the same issue using 0.6.0. I reverted back to 0.5.7 and was no longer seeing this issue.

**Comment by indrimuska** [comment]
Sorry guys for this, can you please tell me your OS and browser, please? Thanks

**Comment by fourgates** [comment]
I tested both Windows 7 and mac OSX using chrome.

**Comment by indrimuska** [comment]
Ok thanks.
Also, can you please check out [this plunker](http://plnkr.co/edit/4sIvTXeZQfovg4wY1zGy?p=preview) and let me know if it works on your platforms?

**Comment by fourgates** [comment]
It does not seem to be fixed in your plunker.

**Comment by micflan** [comment]
@indrimuska – not fixed in the plunker for me.

I'm using Chrome 52 on Mac OSX 10.10.5. More browser/platform details here: http://whatsmybrowser.org/b/VYTB4YZ

Thanks for looking into this. Version 0.5.7 is working for me and is just the date-picker I'd been searching for. Hopefully this bug doesn't chew up too much of your time!

**Comment by LuisEGR** [comment]
Same bug here!, Windows 7 

Google Chrome	52.0.2743.116 (Build oficial) m (32 bits)

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

JavaScript	V8 5.2.361.49


Also in the webpage( http://indrimuska.github.io/angular-moment-picker/ )
Any of the pickers works, they show the picker but when clicking anyone the scope doesn't change, same with the plunker from here.

**Comment by indrimuska** [comment]
Sorry guys, I have to rely on you for this issue, since I am not able to reproduce on any device I have.

As you maybe already know, the problem belongs to [this piece of code](https://github.com/indrimuska/angular-moment-picker/blob/master/src/angular-moment-picker.js#L676-L681): "focus" event on the input (text input or `<div>`) causes the picker to show (opening), while "blur" event hides the picker itself. The problem is that, if you click in the picker dialog the browser fires the "blur" event on the input, so that the picker will be closed.

To avoid this, I want to listen to "mousedown" event -instead of "click" (in the current release)- on the picker, to force input focus every time the user clicks somewhere inside the dialog.

Please, check out [this plunker](http://plnkr.co/edit/4sIvTXeZQfovg4wY1zGy?p=preview) and let me know if it works even for you.
Thanks :)

**Comment by LuisEGR** [comment]
I've tested your plunker and it works!

**Comment by jenspettersson68** [comment]
I can also reproduce the problem (if I click slowly). But as said, the plunker seems to work :)

**Comment by indrimuska** [comment]
Fine, if it works for all of you, then I'm going to pack the fix for the next release.
Thanks guys!

**Comment by indrimuska** [comment]
FYI, this is fixed on latest release [v0.6.3](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.6.3).

**Comment by chqy24** [comment]
That plunker does work, but v0.6.3 seems not work for me.

**Comment by lfreneda** [comment]
still not working.. is not working also on http://indrimuska.github.io/angular-moment-picker/

:cry:

**Comment by indrimuska** [comment]
Just verified the issue stil persist. I'm working on this. Sorry guys.

**Comment by indrimuska** [comment]
It is caused by a wrong position of the `$scope.focusInput` method.
Give me 5 minutes to prep a new release.

**Comment by lfreneda** [comment]
@indrimuska thank you so much :grinning:

**Comment by indrimuska** [comment]
I've released release [v0.6.4](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.6.4).
Please, let me know if the issue still persists.

**Comment by chqy24** [comment]
Works for me now, thanks.

**Comment by LuisEGR** [comment]
Working for me too, thanks!

**Comment by indrimuska** [comment]
I think this issue is fixed now and should be close. Thanks to all of you. :)

**Comment by dementhius** [comment]
Hello @indrimuska 
I have just installed your ,library and Ihave the same problem as @vedard in .I´m using library version 0.9.11 with AngularJS 1.4.3 and Ionic framework.

Could be possible a conflict with any Ionic FMW function?

Thx

**Comment by indrimuska** [comment]
Hi @dementhius I added your issue to the task list in #173, would you please provide a working sample to reproduce this? Many thanks :)

**Comment by ithan1985** [comment]
i have the same problem ver /0.10.2
