### ISSUE TITLE
Picker does not start at current ng-model value

### ISSUE THREAD

**Issue by tartillo** [indrimuska/angular-moment-picker#93]
Hi @indrimuska ,

I've noticed that the moment-picker does not start at the value of ng-model, but instead at the current moment(), i.e. right now.

I have a use case of a fixed date where I only want to set the hour, but the date is changed as well (to today) because the moment-picker initiates on today. Check out this [plunker](https://plnkr.co/edit/jt33xOS8ysBgmMDTwMgE?p=preview) for an example how a date next year is changed to today, while the user can only choose the time.

**Comment by indrimuska** [comment]
Hi @tartillo, I saw your plunker and the problem seems to stand in the initialization of first visible view. Indeed, as you can see there's no time highlighted in the current year, you need to go to the next one to see the blue highlighted day/time.

I'm going to fix this as soon as I can. Thanks!

**Comment by indrimuska** [comment]
Check out latest release v0.8.1, this should be fixed!

**Comment by tartillo** [comment]
Hi @indrimuska,
Thanks for the quick response, but the issue remains! It's not about the highlighting but the underlying value.
The date is changed whereas only the time should change.
Updated the [plunker](https://plnkr.co/edit/WhoupuqTDCuRazjKAR5S?p=preview) with an explicit check. You see the year switch from 2017 (initial value) to 2016 (today's year).

**Comment by josephpedro** [comment]
Hi @indrimuska,

I also have the same problem.

**Comment by indrimuska** [comment]
Latest version seems not affected about this bug.
Could anyone of you verify this?
